# Don't build if build request was triggered by Travis
# if: sender != traviscibot OR sender != Travis
if: commit_message != 'Deploy AndreMaz/awesome-moleculer to github.com/AndreMaz/awesome-moleculer.git:master'

dist: xenial
language: generic
rvm:
  - 2.2
# node_js: "12"

cache:
  directories:
  - node_modules

before_script:
  - npm install
  - gem install awesome_bot
script:
    - npm run build # Build new Readme
    - npm run gen # Build modules.yml for moleculer site
    - awesome_bot README.md --allow-redirect --allow-ssl --skip-save-results --allow-dupe # Check the links
    - bash trigger.sh
deploy:
  provider: pages
  target_branch: master # Push to master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
