language: ruby
rvm:
  - 2.2
node_js: "12"

before_script:
  - gem install awesome_bot
  - npm install
script:
  - awesome_bot README.md --allow-redirect --allow-ssl --skip-save-results --allow-dupe
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master